app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /

default:
    path:  /default
    defaults: { _controller: AppBundle:Default:index }

home:
    path:  /
    defaults: { _controller: AppBundle:Index:index }
    
serie:
    path:  /serie/{slug}
    defaults: { _controller: AppBundle:Serie:view }
    
season:
  path:  /serie/{slug}/season/{number}
  defaults: { _controller: AppBundle:Season:view }
    
episode:
  path:  /serie/{slug}/season/{seasonNumber}/episode/{episodeNumber}
  defaults: { _controller: AppBundle:Episode:view }
  