# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    serviceBS:
        class:      AppBundle\Service\BS
        arguments:  ["%bs_server%","%bs_api_key%","%bs_user%","%bs_md5_password%"]
    serviceRestTvdb:
        class:      AppBundle\Service\RestTvdb
        arguments:  ["%tvdb_server_rest%","%tvdb_api_key%","%tvdb_user_name%","%tvdb_user_key%"]
    serviceTmdb:
        class:      AppBundle\Service\Tmdb
        arguments:  ["%tmdb_server_rest%","%tmdb_api_key%"]        
    serviceFanart:
        class:      AppBundle\Service\Fanart
        arguments:  ["%fanart_server%","%fanart_client_key%","%fanart_api_key%"]    
    serviceTrackt:
        class:      AppBundle\Service\Trackt
        arguments:  ["%trackt_server%","%trackt_client_id%","%trackt_client_secret%","%trackt_access_token%"]
    servicePushBullet:
        class:      AppBundle\Service\PushBullet
        arguments:  ["%pushbullet_server%","%pushbullet_token%"]
        