<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadListRepository extends EntityRepository
{
   
}
