<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpisodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpisodeRepository extends EntityRepository
{
    public function getUndownloaded()
    {
        return $this->createQueryBuilder('e')
            ->where('e.downloaded = 0')
            ->getQuery()
            ->getResult(); 
    }
    
    public function getWatched()
    {
        return $this->createQueryBuilder('e')
            ->where('e.watched = 1')
            ->getQuery()
            ->getResult(); 
    }
}
