<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Serie;
/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExisting($name, Serie $serie)
    {
        $name = addslashes($name);
        return $this->createQueryBuilder('p')
            ->where('p.serie = :serie and p.name = :name')
            ->setParameters(array('serie' => $serie, 'name' => $name)) 
            ->getQuery()
            ->getResult();
    }
}
