<?php

namespace AppBundle\Entity;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlugAndNumber($slug,$number)
    {
        return $this->createQueryBuilder('season')
            ->innerJoin('season.serie','serie')
            ->where('serie.slug = :slug and season.number= :number')
            ->setParameters(array('slug' => $slug,'number' => $number)) 
            ->getQuery()
            ->getResult();
    }
}
