<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonRepository extends EntityRepository
{
    public function getActive()
    {
        return $this->createQueryBuilder('s')
            ->where('s.nbEpisode is not NULL')
            ->getQuery()
            ->getResult();
    }
}
