<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends EntityRepository
{
    public function getUnfinished()
    {
        return $this->createQueryBuilder('s')
            ->where('s.remaining > 0 and s.archived = 0')
            ->getQuery()
            ->getResult();
    }
    
    public function findAll()
    {
        return $this->createQueryBuilder('s')
            ->orderBy('s.name')
            ->getQuery()
            ->getResult();
    }
    
    public function findExisting($id, $name)
    {
        $name = addslashes($name);
        return $this->createQueryBuilder('s')
            ->where('s.idServiio = :id or s.name = :name')
            ->setParameters(array('id' => $id, 'name' => $name)) 
            ->getQuery()
            ->getResult();
    }
    
}
